"""
LLM Fallback Extractor
======================
Second-pass extractor for unresolved paragraphs from regex-based extraction.

Workflow:
1. Read outputs/queue_for_llm.csv generated by extract_definitions.py
2. Run structured extraction with Pydantic schema via LLM
3. Export validated records to outputs/llm_fallback_results.csv

Usage:
    python scripts/extraction_fallback.py
    python scripts/extraction_fallback.py --dry-run
    python scripts/extraction_fallback.py --model gpt-4.1-mini
    python scripts/extraction_fallback.py --provider ollama --model llama3.1:8b
"""

import argparse
import concurrent.futures
import csv
import importlib
import json
import os
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional

import sys

# Add parent directory to path to import config
sys.path.insert(0, str(Path(__file__).parent.parent))
import config


def validate_with_pydantic(payload: dict) -> dict:
    """Validate extraction payload using Pydantic (loaded lazily at runtime)."""
    try:
        pydantic = importlib.import_module("pydantic")
    except ModuleNotFoundError as err:
        raise RuntimeError(
            "pydantic package is missing. Install dependencies with: pip install -r requirements.txt"
        ) from err

    BaseModel = getattr(pydantic, "BaseModel")
    Field = getattr(pydantic, "Field")

    class ForestDefinitionExtraction(BaseModel):
        concept: str
        definition_text: str
        country: Optional[str] = None
        organization: Optional[str] = None
        year: Optional[int] = Field(default=None, ge=1800, le=2100)
        definition_type: Optional[str] = None
        geographic_scope: Optional[str] = None
        min_area: Optional[float] = None
        min_canopy_cover: Optional[float] = None
        min_height: Optional[float] = None
        min_width: Optional[float] = None
        confidence: float = Field(default=0.0, ge=0.0, le=1.0)
        extraction_notes: Optional[str] = None

    model = ForestDefinitionExtraction.model_validate(payload)
    return model.model_dump()


class LLMFallbackExtractor:
    """Runs second-pass extraction only for queued unresolved paragraphs."""

    def __init__(
        self,
        model: str = "gpt-4o-mini",
        dry_run: bool = False,
        provider: str = "auto",
        workers: int = 1,
        max_retries: int = 2,
        retry_delay: float = 1.0,
    ):
        self.model = model
        self.dry_run = dry_run
        self.provider = provider
        self.workers = max(1, int(workers))
        self.max_retries = max(0, int(max_retries))
        self.retry_delay = max(0.0, float(retry_delay))
        self.client = None

        if self.dry_run:
            return

        if self.provider == "auto":
            self.provider = "openai" if os.getenv("OPENAI_API_KEY") else "ollama"

        if self.provider == "ollama" and self.model == "gpt-4o-mini":
            self.model = "llama3.1:8b"

        if self.provider == "openai":
            self._init_openai_client()
        elif self.provider == "ollama":
            self._check_ollama_available()
        else:
            raise RuntimeError("Invalid provider. Use one of: auto, openai, ollama")

    def _init_openai_client(self):
        """Initialize OpenAI client lazily to keep dry-run mode dependency-light."""
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            raise RuntimeError(
                "OPENAI_API_KEY is not set. Set it, or run with --dry-run."
            )

        try:
            openai_mod = importlib.import_module("openai")
            OpenAI = getattr(openai_mod, "OpenAI")
        except ImportError as err:
            raise RuntimeError(
                "openai package is missing. Install dependencies with: pip install -r requirements.txt"
            ) from err

        self.client = OpenAI(api_key=api_key)

    def _check_ollama_available(self):
        """Check whether local Ollama server is reachable."""
        req = urllib.request.Request(
            url="http://localhost:11434/api/tags",
            method="GET",
        )
        try:
            with urllib.request.urlopen(req, timeout=3) as response:
                if response.status != 200:
                    raise RuntimeError("Ollama is not responding correctly on http://localhost:11434")
        except Exception as err:
            raise RuntimeError(
                "Ollama not available at http://localhost:11434. Start Ollama first (e.g., 'ollama serve')."
            ) from err

    def _prompt_messages(self, concept: str, paragraph: str):
        system_prompt = (
            "You are an information extraction system. "
            "Extract a forest-related definition into strict JSON with the requested schema. "
            "Do not invent facts. Use null when information is missing."
        )

        user_prompt = (
            "Extract structured data from this paragraph.\n\n"
            f"Concept candidate: {concept}\n"
            f"Paragraph:\n{paragraph}\n\n"
            "Return a JSON object with these keys exactly:\n"
            "concept, definition_text, country, organization, year, definition_type, geographic_scope, "
            "min_area, min_canopy_cover, min_height, min_width, confidence, extraction_notes"
        )

        return [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]

    def extract_structured(self, concept: str, paragraph: str) -> dict:
        """Extract one paragraph with either dry-run heuristic or LLM call."""
        if self.dry_run:
            return validate_with_pydantic(
                {
                    "concept": concept.capitalize(),
                    "definition_text": paragraph,
                    "country": None,
                    "organization": None,
                    "year": None,
                    "definition_type": None,
                    "geographic_scope": None,
                    "min_area": None,
                    "min_canopy_cover": None,
                    "min_height": None,
                    "min_width": None,
                    "confidence": 0.2,
                    "extraction_notes": "dry_run_mode",
                }
            )

        if self.provider == "ollama":
            return self._extract_structured_ollama(concept, paragraph)

        completion = self.client.chat.completions.create(
            model=self.model,
            temperature=0,
            response_format={"type": "json_object"},
            messages=self._prompt_messages(concept, paragraph),
        )

        content = completion.choices[0].message.content or "{}"
        payload = json.loads(content)
        return validate_with_pydantic(payload)

    def _extract_structured_ollama(self, concept: str, paragraph: str) -> dict:
        """Extract structured JSON using local Ollama chat API."""
        messages = self._prompt_messages(concept, paragraph)
        body = {
            "model": self.model,
            "messages": messages,
            "stream": False,
            "format": "json",
            "options": {"temperature": 0},
        }

        req = urllib.request.Request(
            url="http://localhost:11434/api/chat",
            method="POST",
            data=json.dumps(body).encode("utf-8"),
            headers={"Content-Type": "application/json"},
        )

        try:
            with urllib.request.urlopen(req, timeout=120) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as err:
            details = err.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"Ollama HTTP error: {err.code} {details}") from err
        except Exception as err:
            raise RuntimeError(f"Ollama request failed: {err}") from err

        content = payload.get("message", {}).get("content", "{}")
        parsed = json.loads(content)
        return validate_with_pydantic(parsed)

    def _process_row(self, row: dict) -> dict:
        """Process a single row with retry logic and return output-ready record."""
        paragraph_id = row.get("paragraph_id", "")
        concept = row.get("concept", "forest")
        reason = row.get("reason", "")
        text = row.get("text", "")

        last_error = None
        for attempt in range(self.max_retries + 1):
            try:
                extracted = self.extract_structured(concept, text)
                return {
                    "paragraph_id": paragraph_id,
                    "concept": extracted.get("concept", concept),
                    "queue_reason": reason,
                    "status": "ok",
                    "definition_text": extracted.get("definition_text", ""),
                    "country": extracted.get("country") or "",
                    "organization": extracted.get("organization") or "",
                    "year": extracted.get("year") or "",
                    "definition_type": extracted.get("definition_type") or "",
                    "geographic_scope": extracted.get("geographic_scope") or "",
                    "min_area": extracted.get("min_area") or "",
                    "min_canopy_cover": extracted.get("min_canopy_cover") or "",
                    "min_height": extracted.get("min_height") or "",
                    "min_width": extracted.get("min_width") or "",
                    "confidence": extracted.get("confidence", ""),
                    "extraction_notes": extracted.get("extraction_notes") or "",
                    "error": "",
                    "raw_text": text,
                }
            except Exception as err:
                last_error = err
                if attempt < self.max_retries:
                    sleep_seconds = self.retry_delay * (2 ** attempt)
                    if sleep_seconds > 0:
                        time.sleep(sleep_seconds)

        return {
            "paragraph_id": paragraph_id,
            "concept": concept,
            "queue_reason": reason,
            "status": "error",
            "definition_text": "",
            "country": "",
            "organization": "",
            "year": "",
            "definition_type": "",
            "geographic_scope": "",
            "min_area": "",
            "min_canopy_cover": "",
            "min_height": "",
            "min_width": "",
            "confidence": "",
            "extraction_notes": "",
            "error": str(last_error) if last_error else "unknown_error",
            "raw_text": text,
        }

    def process_queue(self, queue_path: Path, output_path: Path, limit: Optional[int] = None):
        """Process queued unresolved rows and export structured fallback results."""
        if not queue_path.exists():
            raise FileNotFoundError(
                f"Queue file not found: {queue_path}. Run scripts/extract_definitions.py first."
            )

        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(queue_path, "r", encoding="utf-8", newline="") as in_file:
            rows = list(csv.DictReader(in_file))

        if limit is not None and limit > 0:
            rows = rows[:limit]

        if not rows:
            print("[INFO] Queue is empty. Nothing to process.")
            return

        print(
            f"[*] Processing {len(rows)} queued paragraphs with provider={self.provider} "
            f"model={self.model} workers={self.workers} retries={self.max_retries}"
        )

        fieldnames = [
            "paragraph_id",
            "concept",
            "queue_reason",
            "status",
            "definition_text",
            "country",
            "organization",
            "year",
            "definition_type",
            "geographic_scope",
            "min_area",
            "min_canopy_cover",
            "min_height",
            "min_width",
            "confidence",
            "extraction_notes",
            "error",
            "raw_text",
        ]

        success_count = 0
        fail_count = 0

        with open(output_path, "w", encoding="utf-8", newline="") as out_file:
            writer = csv.DictWriter(out_file, fieldnames=fieldnames)
            writer.writeheader()

            processed = 0
            if self.workers == 1:
                for row in rows:
                    result = self._process_row(row)
                    writer.writerow(result)
                    if result.get("status") == "ok":
                        success_count += 1
                    else:
                        fail_count += 1
                    processed += 1
                    if processed % 100 == 0:
                        print(f"    progress: {processed}/{len(rows)}")
            else:
                with concurrent.futures.ThreadPoolExecutor(max_workers=self.workers) as pool:
                    futures = [pool.submit(self._process_row, row) for row in rows]
                    for future in concurrent.futures.as_completed(futures):
                        result = future.result()
                        writer.writerow(result)
                        if result.get("status") == "ok":
                            success_count += 1
                        else:
                            fail_count += 1
                        processed += 1
                        if processed % 100 == 0:
                            print(f"    progress: {processed}/{len(rows)}")

        print(f"[OK] Fallback extraction complete: success={success_count}, failed={fail_count}")
        print(f"[OK] Results written to: {output_path}")


def parse_args():
    parser = argparse.ArgumentParser(description="Run LLM fallback extraction on unresolved paragraphs")
    parser.add_argument(
        "--queue",
        type=Path,
        default=config.QUEUE_FOR_LLM_CSV,
        help="Path to queue_for_llm.csv",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=config.LLM_FALLBACK_RESULTS_CSV,
        help="Output CSV for structured fallback results",
    )
    parser.add_argument(
        "--provider",
        type=str,
        choices=["auto", "openai", "ollama"],
        default="auto",
        help="LLM provider: auto (default), openai, or ollama (local)",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="gpt-4o-mini",
        help="Model name (OpenAI model or Ollama local model)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Skip API calls and generate schema-shaped placeholder output",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of concurrent workers for row processing (default: 1)",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=2,
        help="Retries per row on extraction failure (default: 2)",
    )
    parser.add_argument(
        "--retry-delay",
        type=float,
        default=1.0,
        help="Base retry delay in seconds (default: 1.0, exponential backoff)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Process only first N queued rows (0 = all rows)",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    extractor = LLMFallbackExtractor(
        model=args.model,
        dry_run=args.dry_run,
        provider=args.provider,
        workers=args.workers,
        max_retries=args.max_retries,
        retry_delay=args.retry_delay,
    )
    extractor.process_queue(args.queue, args.output, limit=args.limit)


if __name__ == "__main__":
    main()
